FROM picoded/ubuntu-openjdk-8-jdk AS builder
LABEL maintainer="vicknesh22@gmail.com"
# RUN using non root user
# RUN useradd -u 8877 dock

#install maven
#RUN apt-get install openjdk-8-jdk openjdk-8-jre
#ENV JAVA_HOME  /usr/lib/jvm/java-8-openjdk-amd64

RUN apt-get update -y && apt-get install -y maven
#add maven dependencies
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
ENV MAVEN_HOME /usr/share/maven

RUN apt-get install -y git && mkdir /opt/samplecode && cd /opt/samplecode && git clone https://github.com/spring-projects/spring-petclinic.git
WORKDIR /opt/samplecode
RUN cd spring-petclinic &&  mvn clean install -f /opt/samplecode/spring-petclinic/pom.xml &&  ls -lrt /opt/samplecode/spring-petclinic/target/


FROM tomcat:jdk8
ENV CATALINA_HOME /usr/local/tomcat/
COPY --from=builder /opt/samplecode/*.jar /CATALINA_HOME/webapps/
CMD ["catalina.sh" "run"]
EXPOSE 8080
